[2024-08-31 14:26:56] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-08-31 14:26:56] [INFO    ] discord.client: logging in using static token
[2024-08-31 14:26:57] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: b56ac2d55e650bdccd2c60a4336f396d).
[2024-08-31 14:27:42] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-08-31 14:27:42] [INFO    ] discord.client: logging in using static token
[2024-08-31 14:27:43] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 070a98dd21b250d90e622128afd8033c).
[2024-08-31 15:02:32] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session b56ac2d55e650bdccd2c60a4336f396d.
[2024-08-31 18:05:48] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-08-31 18:05:48] [INFO    ] discord.client: logging in using static token
[2024-08-31 18:05:49] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e5f6ed61e8a684780094bc00c2f496b0).
[2024-08-31 18:05:51] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/home/honza/24-7-discord-music-bot-main/24-7-discord-music-bot-main/bot.py", line 22, in on_ready
    voice_client = await channel.connect()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/abc.py", line 1958, in connect
    voice: T = cls(client, self)
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/discord/voice_client.py", line 220, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice
[2024-08-31 18:15:52] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 070a98dd21b250d90e622128afd8033c.
[2024-10-16 18:42:33] [INFO    ] discord.client: logging in using static token
[2024-10-16 18:42:33] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-10-16 18:42:33] [INFO    ] discord.client: logging in using static token
[2024-10-16 18:42:35] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 253fb969a8989fdf34e358880811e523).
[2024-10-16 18:42:35] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 7ca0cb68647791383af4823bf8ec5554).
[2024-10-16 18:42:37] [INFO    ] discord.voice_state: Connecting to voice...
[2024-10-16 18:42:37] [INFO    ] discord.voice_state: Starting voice handshake... (connection attempt 1)
[2024-10-16 18:42:37] [INFO    ] discord.voice_state: Voice handshake complete. Endpoint found: warsaw10094.discord.media
[2024-10-16 18:42:37] [INFO    ] discord.voice_state: Voice connection complete.
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:1: Broken pipe
Error closing file pipe:1: Broken pipe
[2024-10-16 20:19:15] [INFO    ] discord.client: logging in using static token
[2024-10-16 20:19:15] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-10-16 20:19:15] [INFO    ] discord.client: logging in using static token
[2024-10-16 20:19:16] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 9370d62d9ee6ad36a79ece3b31497ee3).
[2024-10-16 20:19:17] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 9ac03b71f13e9df90c4eb612ad5813d3).
[2024-10-16 20:19:19] [INFO    ] discord.voice_state: Connecting to voice...
[2024-10-16 20:19:19] [INFO    ] discord.voice_state: Starting voice handshake... (connection attempt 1)
[2024-10-16 20:19:19] [INFO    ] discord.voice_state: Voice handshake complete. Endpoint found: warsaw10100.discord.media
[2024-10-16 20:19:19] [INFO    ] discord.voice_state: Voice connection complete.
[2024-10-16 20:21:15] [INFO    ] discord.player: ffmpeg process 1908 has not terminated. Waiting to terminate...
[2024-10-16 20:21:15] [INFO    ] discord.player: ffmpeg process 1908 should have terminated with a return code of -9.
[2024-10-16 20:23:11] [INFO    ] discord.player: ffmpeg process 1919 has not terminated. Waiting to terminate...
[2024-10-16 20:23:11] [INFO    ] discord.player: ffmpeg process 1919 should have terminated with a return code of -9.
Already up to date.
[2024-10-16 20:23:12] [INFO    ] discord.client: logging in using static token
[2024-10-16 20:23:12] [WARNING ] discord.ext.commands.bot: Privileged message content intent is missing, commands may not work as expected.
[2024-10-16 20:23:12] [INFO    ] discord.client: logging in using static token
[2024-10-16 20:23:13] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 76d142c541cbc8ca5e998853a3847895).
[2024-10-16 20:23:13] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 0ef956648b591690469bd6a642825923).
[2024-10-16 20:23:15] [INFO    ] discord.voice_state: Connecting to voice...
[2024-10-16 20:23:15] [INFO    ] discord.voice_state: Starting voice handshake... (connection attempt 1)
[2024-10-16 20:23:16] [ERROR   ] discord.voice_state: Disconnected from voice... Reconnecting in 1.47s.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/voice_state.py", line 598, in _poll_voice_ws
    await self.ws.poll_event()
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 1037, in poll_event
    raise ConnectionClosed(self.ws, shard_id=None, code=self._close_code)
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 4006
[2024-10-16 20:23:16] [INFO    ] discord.voice_state: Voice handshake complete. Endpoint found: warsaw10100.discord.media
[2024-10-16 20:23:16] [INFO    ] discord.voice_state: Voice connection complete.
[2024-10-16 20:23:17] [INFO    ] discord.voice_state: The voice handshake is being terminated for Channel ID 1208492447953453086 (Guild ID 1171405828201390180)
[2024-10-16 20:23:17] [INFO    ] discord.voice_state: Connecting to voice...
[2024-10-16 20:23:17] [INFO    ] discord.voice_state: Starting voice handshake... (connection attempt 1)
[2024-10-16 20:23:17] [ERROR   ] discord.voice_state: Disconnected from voice... Reconnecting in 1.92s.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/voice_state.py", line 598, in _poll_voice_ws
    await self.ws.poll_event()
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 1037, in poll_event
    raise ConnectionClosed(self.ws, shard_id=None, code=self._close_code)
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 4006
[2024-10-16 20:23:17] [INFO    ] discord.voice_state: Voice handshake complete. Endpoint found: warsaw10100.discord.media
[2024-10-16 20:23:18] [INFO    ] discord.voice_state: Voice connection complete.
[2024-10-16 20:23:19] [INFO    ] discord.voice_state: The voice handshake is being terminated for Channel ID 1208492447953453086 (Guild ID 1171405828201390180)
[2024-10-16 20:23:19] [INFO    ] discord.player: ffmpeg process 1953 has not terminated. Waiting to terminate...
[2024-10-16 20:23:19] [INFO    ] discord.voice_state: Connecting to voice...
[2024-10-16 20:23:19] [INFO    ] discord.voice_state: Starting voice handshake... (connection attempt 1)
[2024-10-16 20:23:19] [INFO    ] discord.player: ffmpeg process 1953 should have terminated with a return code of -9.
[2024-10-16 20:23:19] [ERROR   ] discord.voice_state: Disconnected from voice... Reconnecting in 3.68s.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/voice_state.py", line 598, in _poll_voice_ws
    await self.ws.poll_event()
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 1037, in poll_event
    raise ConnectionClosed(self.ws, shard_id=None, code=self._close_code)
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 4006
[2024-10-16 20:23:19] [INFO    ] discord.voice_state: Voice handshake complete. Endpoint found: warsaw10100.discord.media
[2024-10-16 20:23:20] [INFO    ] discord.voice_state: Voice connection complete.
[2024-10-16 20:23:23] [INFO    ] discord.voice_state: The voice handshake is being terminated for Channel ID 1208492447953453086 (Guild ID 1171405828201390180)
[2024-10-16 20:23:23] [INFO    ] discord.voice_state: Connecting to voice...
[2024-10-16 20:23:23] [INFO    ] discord.voice_state: Starting voice handshake... (connection attempt 1)
[2024-10-16 20:23:23] [ERROR   ] discord.voice_state: Disconnected from voice... Reconnecting in 1.62s.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/voice_state.py", line 598, in _poll_voice_ws
    await self.ws.poll_event()
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 1037, in poll_event
    raise ConnectionClosed(self.ws, shard_id=None, code=self._close_code)
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 4006
[2024-10-16 20:23:23] [INFO    ] discord.voice_state: Voice handshake complete. Endpoint found: warsaw10100.discord.media
[2024-10-16 20:23:24] [INFO    ] discord.voice_state: Voice connection complete.
[2024-10-16 20:23:25] [INFO    ] discord.voice_state: The voice handshake is being terminated for Channel ID 1208492447953453086 (Guild ID 1171405828201390180)
[2024-10-16 20:23:25] [INFO    ] discord.voice_state: Connecting to voice...
[2024-10-16 20:23:25] [INFO    ] discord.voice_state: Starting voice handshake... (connection attempt 1)
[2024-10-16 20:23:25] [ERROR   ] discord.voice_state: Disconnected from voice... Reconnecting in 1.26s.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/voice_state.py", line 598, in _poll_voice_ws
    await self.ws.poll_event()
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 1037, in poll_event
    raise ConnectionClosed(self.ws, shard_id=None, code=self._close_code)
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 4006
[2024-10-16 20:23:25] [INFO    ] discord.voice_state: Voice handshake complete. Endpoint found: warsaw10100.discord.media
[2024-10-16 20:23:25] [INFO    ] discord.voice_state: Voice connection complete.
[2024-10-16 20:23:26] [INFO    ] discord.voice_state: The voice handshake is being terminated for Channel ID 1208492447953453086 (Guild ID 1171405828201390180)
[2024-10-16 20:23:26] [INFO    ] discord.voice_state: Connecting to voice...
[2024-10-16 20:23:26] [INFO    ] discord.voice_state: Starting voice handshake... (connection attempt 1)
[2024-10-16 20:23:26] [ERROR   ] discord.voice_state: Disconnected from voice... Reconnecting in 0.84s.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/voice_state.py", line 598, in _poll_voice_ws
    await self.ws.poll_event()
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 1037, in poll_event
    raise ConnectionClosed(self.ws, shard_id=None, code=self._close_code)
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 4006
[2024-10-16 20:23:26] [INFO    ] discord.voice_state: Voice handshake complete. Endpoint found: warsaw10100.discord.media
[2024-10-16 20:23:27] [INFO    ] discord.voice_state: Voice connection complete.
[2024-10-16 20:23:27] [INFO    ] discord.voice_state: The voice handshake is being terminated for Channel ID 1208492447953453086 (Guild ID 1171405828201390180)
[2024-10-16 20:23:27] [INFO    ] discord.voice_state: Connecting to voice...
[2024-10-16 20:23:27] [INFO    ] discord.voice_state: Starting voice handshake... (connection attempt 1)
[2024-10-16 20:23:27] [ERROR   ] discord.voice_state: Disconnected from voice... Reconnecting in 0.76s.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/voice_state.py", line 598, in _poll_voice_ws
    await self.ws.poll_event()
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 1037, in poll_event
    raise ConnectionClosed(self.ws, shard_id=None, code=self._close_code)
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 4006
[2024-10-16 20:23:27] [INFO    ] discord.voice_state: Voice handshake complete. Endpoint found: warsaw10100.discord.media
[2024-10-16 20:23:28] [INFO    ] discord.voice_state: Voice connection complete.
[2024-10-16 20:23:28] [INFO    ] discord.voice_state: The voice handshake is being terminated for Channel ID 1208492447953453086 (Guild ID 1171405828201390180)
[2024-10-16 20:23:28] [INFO    ] discord.voice_state: Connecting to voice...
[2024-10-16 20:23:28] [INFO    ] discord.voice_state: Starting voice handshake... (connection attempt 1)
[2024-10-16 20:23:28] [ERROR   ] discord.voice_state: Disconnected from voice... Reconnecting in 10.93s.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/voice_state.py", line 598, in _poll_voice_ws
    await self.ws.poll_event()
  File "/usr/local/lib/python3.11/dist-packages/discord/gateway.py", line 1037, in poll_event
    raise ConnectionClosed(self.ws, shard_id=None, code=self._close_code)
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 4006
[2024-10-16 20:23:28] [INFO    ] discord.voice_state: Voice handshake complete. Endpoint found: warsaw10100.discord.media
[2024-10-16 20:23:39] [INFO    ] discord.voice_state: The voice handshake is being terminated for Channel ID 1208492447953453086 (Guild ID 1171405828201390180)
[2024-10-16 20:23:39] [INFO    ] discord.voice_state: Connecting to voice...
[2024-10-16 20:23:39] [INFO    ] discord.voice_state: Starting voice handshake... (connection attempt 1)
[2024-10-16 20:23:40] [INFO    ] discord.voice_state: Voice handshake complete. Endpoint found: warsaw10100.discord.media
[2024-10-16 20:23:58] [INFO    ] discord.voice_state: Voice connection complete.
[2024-10-16 20:23:58] [INFO    ] discord.player: ffmpeg process 1930 has not terminated. Waiting to terminate...
[2024-10-16 20:23:58] [INFO    ] discord.player: ffmpeg process 1930 should have terminated with a return code of -9.
[2024-10-16 20:25:07] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/home/honza/24-7-discord-music-bot-main/24-7-discord-music-bot-main/bot.py", line 30, in on_ready
    voice_client.play(discord.FFmpegPCMAudio(source=file_path))
  File "/usr/local/lib/python3.11/dist-packages/discord/voice_client.py", line 478, in play
    raise ClientException('Not connected to voice.')
discord.errors.ClientException: Not connected to voice.
[2024-10-16 20:25:07] [INFO    ] discord.player: ffmpeg process 1969 has not terminated. Waiting to terminate...
[2024-10-16 20:25:07] [INFO    ] discord.player: ffmpeg process 1969 should have terminated with a return code of -9.
[2024-10-16 20:26:08] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 0ef956648b591690469bd6a642825923.
